// Generated by CoffeeScript 1.12.7
(function() {
  var Base, Widget, driver,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  driver = require('./webdriver');

  Base = require('./base');

  Widget = (function(superClass) {
    var generateApiMethod, i, len, method, ref;

    extend(Widget, superClass);

    Widget.url = null;

    Widget.visit = function(wait) {
      var screen;
      if (wait == null) {
        wait = 5000;
      }
      driver.api.url(this.url);
      screen = new this();
      screen.waitForExist(wait);
      return screen;
    };

    Widget.prototype.driver = null;

    Widget.prototype.selector = null;

    function Widget(selector, driver1) {
      this.driver = driver1 != null ? driver1 : driver.api;
      if (selector != null) {
        this.selector = selector;
      }
      if (!typeof this.selector === 'string') {
        throw new Error("Invalid selector given: " + this.selector);
      }
    }

    Widget.prototype.find = function(nestedSelector) {
      return new Widget(this.selector + " " + nestedSelector);
    };

    Widget.prototype.hasText = function(expected) {
      return this.getText().should.eventually.become(expected);
    };

    Widget.API = ['addValue', 'clearElement', 'click', 'doubleClick', 'dragAndDrop', 'leftClick', 'middleClick', 'moveToObject', 'rightClick', 'setValue', 'submitForm', 'getAttribute', 'getCssProperty', 'getElementSize', 'getHTML', 'getLocation', 'getLocationInView', 'getSource', 'getTagName', 'getText', 'getTitle', 'getValue', 'isEnabled', 'isExisting', 'isSelected', 'isVisible', 'waitForChecked', 'waitForEnabled', 'waitForExist', 'waitForSelected', 'waitForText', 'waitForValue', 'waitForVisible'];

    generateApiMethod = function(method) {
      return function() {
        var callArgs;
        callArgs = Array.prototype.slice.call(arguments);
        callArgs.unshift(this.selector);
        return this.driver[method].apply(this.driver, callArgs);
      };
    };

    ref = Widget.API;
    for (i = 0, len = ref.length; i < len; i++) {
      method = ref[i];
      Widget.prototype[method] = generateApiMethod(method);
    }

    return Widget;

  })(Base);

  module.exports = Widget;

}).call(this);
